import { type User, type Category, type Ticket, type Message, type AgentWorkload } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 1,
    firstName: 'Alex',
    lastName: 'Rivera',
    email: 'admin@sentinel.com',
    role: 'ADMIN',
    status: 'ONLINE',
    avatar: 'https://i.pravatar.cc/150?u=1',
    isActive: true,
  },
  {
    id: 2,
    firstName: 'Mark',
    lastName: 'Jensen',
    email: 'mark@sentinel.com',
    role: 'SUPPORT_AGENT',
    status: 'ONLINE',
    avatar: 'https://i.pravatar.cc/150?u=2',
    isActive: true,
  },
  {
    id: 3,
    firstName: 'Sarah',
    lastName: 'Mitchell',
    email: 'sarah@sentinel.com',
    role: 'SUPPORT_AGENT',
    status: 'ONLINE',
    avatar: 'https://i.pravatar.cc/150?u=3',
    isActive: true,
  },
  {
    id: 4,
    firstName: 'Elena',
    lastName: 'Rossi',
    email: 'elena@client.com',
    role: 'CLIENT',
    status: 'ONLINE',
    avatar: 'https://i.pravatar.cc/150?u=4',
    isActive: true,
  },
  {
    id: 5,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@client.com',
    role: 'CLIENT',
    status: 'OFFLINE',
    avatar: 'https://i.pravatar.cc/150?u=5',
    isActive: true,
  },
  {
    id: 6,
    firstName: 'David',
    lastName: 'Chen',
    email: 'david@sentinel.com',
    role: 'SUPPORT_AGENT',
    status: 'AWAY',
    avatar: 'https://i.pravatar.cc/150?u=6',
    isActive: true,
  },
  {
    id: 7,
    firstName: 'Lisa',
    lastName: 'Kudrow',
    email: 'lisa@sentinel.com',
    role: 'SUPPORT_AGENT',
    status: 'ONLINE',
    avatar: 'https://i.pravatar.cc/150?u=7',
    isActive: false,
  },
  {
    id: 8,
    firstName: 'Robert',
    lastName: 'Pattinson',
    email: 'robert@sentinel.com',
    role: 'SUPPORT_AGENT',
    status: 'OFFLINE',
    avatar: 'https://i.pravatar.cc/150?u=8',
    isActive: true,
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Infrastructure' },
  { id: 2, name: 'Billing' },
  { id: 3, name: 'Technical Support' },
  { id: 4, name: 'Frontend' },
  { id: 5, name: 'Information' },
];

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 1,
    title: 'Enterprise Cluster Connectivity Failure',
    description: 'Secondary node in US-East-1 is failing heartbeats.',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    createdDate: '2024-10-20T14:32:00Z',
    categoryId: 1,
    createdBy: 4,
    assignedAgent: 2,
  },
  {
    id: 2,
    title: 'API Connection Timeout - Tier 2',
    description: 'Intermittent timeouts when calling checkout API.',
    priority: 'HIGH',
    status: 'OPEN',
    createdDate: '2024-10-21T15:10:00Z',
    categoryId: 3,
    createdBy: 5,
  },
  {
    id: 3,
    title: 'Billing Discrepancy: Q3 Invoice',
    description: 'Overcharge for storage units.',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    createdDate: '2024-10-19T12:00:00Z',
    resolvedDate: '2024-10-22T09:00:00Z',
    categoryId: 2,
    createdBy: 4,
    assignedAgent: 3,
  },
  {
    id: 4,
    title: 'Frontend CSS alignment issue',
    description: 'Buttons are overlapping on mobile view.',
    priority: 'LOW',
    status: 'CLOSED',
    createdDate: '2024-10-15T10:00:00Z',
    resolvedDate: '2024-10-16T14:00:00Z',
    categoryId: 4,
    createdBy: 5,
    assignedAgent: 2,
  },
  {
    id: 5,
    title: 'Database Migration Error',
    description: 'Failed to migrate legacy data to new schema.',
    priority: 'HIGH',
    status: 'OPEN',
    createdDate: '2024-10-22T08:30:00Z',
    categoryId: 1,
    createdBy: 4,
  },
  {
    id: 6,
    title: 'Password Reset Not Working',
    description: 'Users are not receiving reset emails.',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    createdDate: '2024-10-23T11:20:00Z',
    categoryId: 5,
    createdBy: 5,
    assignedAgent: 3,
  },
  {
    id: 7,
    title: 'Slow Dashboard Loading',
    description: 'Analytics dashboard takes > 10s to load.',
    priority: 'MEDIUM',
    status: 'OPEN',
    createdDate: '2024-10-24T09:15:00Z',
    categoryId: 4,
    createdBy: 4,
  },
  {
    id: 8,
    title: 'SSL Certificate Expiry',
    description: 'Production SSL cert expires in 3 days.',
    priority: 'CRITICAL',
    status: 'OPEN',
    createdDate: '2024-10-24T16:45:00Z',
    categoryId: 1,
    createdBy: 1,
  },
  {
    id: 9,
    title: 'New Feature Request: Dark Mode',
    description: 'Clients are asking for a dark mode option.',
    priority: 'LOW',
    status: 'OPEN',
    createdDate: '2024-10-20T13:00:00Z',
    categoryId: 4,
    createdBy: 5,
  },
  {
    id: 10,
    title: 'Incomplete Documentation',
    description: 'API docs are missing the new endpoints.',
    priority: 'LOW',
    status: 'RESOLVED',
    createdDate: '2024-10-18T14:00:00Z',
    resolvedDate: '2024-10-20T10:00:00Z',
    categoryId: 5,
    createdBy: 4,
    assignedAgent: 2,
  },
  {
    id: 11,
    title: 'Payment Gateway Error',
    description: 'Stripe integration failing for EMEA region.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    createdDate: '2024-10-23T10:00:00Z',
    categoryId: 2,
    createdBy: 5,
    assignedAgent: 6,
  },
  {
    id: 12,
    title: 'Broken Link in Footer',
    description: 'Privacy policy link leads to 404.',
    priority: 'LOW',
    status: 'OPEN',
    createdDate: '2024-10-24T11:00:00Z',
    categoryId: 4,
    createdBy: 4,
  },
  {
    id: 13,
    title: 'Server OOM Crash',
    description: 'Worker node crashed due to memory exhaustion.',
    priority: 'CRITICAL',
    status: 'RESOLVED',
    createdDate: '2024-10-21T02:00:00Z',
    resolvedDate: '2024-10-21T05:00:00Z',
    categoryId: 1,
    createdBy: 1,
    assignedAgent: 2,
  },
  {
    id: 14,
    title: 'Mobile App Crash on Login',
    description: 'iOS users reporting crashes after update.',
    priority: 'HIGH',
    status: 'OPEN',
    createdDate: '2024-10-24T14:00:00Z',
    categoryId: 3,
    createdBy: 5,
  },
  {
    id: 15,
    title: 'Missing Translation: French',
    description: 'Login page missing French translations.',
    priority: 'LOW',
    status: 'OPEN',
    createdDate: '2024-10-22T16:00:00Z',
    categoryId: 4,
    createdBy: 4,
  },
  {
    id: 16,
    title: 'Database Query Optimization',
    description: 'Slow queries on the transactions table.',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    createdDate: '2024-10-23T09:00:00Z',
    categoryId: 1,
    createdBy: 1,
    assignedAgent: 8,
  },
  {
    id: 17,
    title: 'Email Notification Delay',
    description: 'Notifications arriving 30 mins late.',
    priority: 'MEDIUM',
    status: 'OPEN',
    createdDate: '2024-10-24T10:30:00Z',
    categoryId: 5,
    createdBy: 5,
  },
  {
    id: 18,
    title: 'Broken Image on Landing Page',
    description: 'Hero image not loading in Safari.',
    priority: 'LOW',
    status: 'RESOLVED',
    createdDate: '2024-10-19T11:00:00Z',
    resolvedDate: '2024-10-19T15:00:00Z',
    categoryId: 4,
    createdBy: 4,
    assignedAgent: 3,
  },
  {
    id: 19,
    title: 'API Rate Limit Issue',
    description: 'Clients hitting limits too early.',
    priority: 'MEDIUM',
    status: 'OPEN',
    createdDate: '2024-10-24T13:00:00Z',
    categoryId: 3,
    createdBy: 5,
  },
  {
    id: 20,
    title: 'Wrong Currency on Checkout',
    description: 'Showing USD instead of EUR for German users.',
    priority: 'HIGH',
    status: 'OPEN',
    createdDate: '2024-10-24T15:30:00Z',
    categoryId: 2,
    createdBy: 4,
  },
  {
    id: 21,
    title: 'Security Patch Required',
    description: 'New CVE found in base image.',
    priority: 'CRITICAL',
    status: 'OPEN',
    createdDate: '2024-10-24T17:00:00Z',
    categoryId: 1,
    createdBy: 1,
  },
  {
    id: 22,
    title: 'Logo Update Request',
    description: 'Marketing wants the new logo in header.',
    priority: 'LOW',
    status: 'OPEN',
    createdDate: '2024-10-23T14:00:00Z',
    categoryId: 4,
    createdBy: 4,
  },
  {
    id: 23,
    title: 'CSV Export Failing',
    description: 'Exporting > 1000 rows fails with timeout.',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    createdDate: '2024-10-23T16:00:00Z',
    categoryId: 3,
    createdBy: 5,
    assignedAgent: 6,
  },
  {
    id: 24,
    title: 'Search Results Inaccurate',
    description: 'Searching for "invoice" returns "users".',
    priority: 'MEDIUM',
    status: 'OPEN',
    createdDate: '2024-10-24T08:00:00Z',
    categoryId: 4,
    createdBy: 4,
  },
  {
    id: 25,
    title: 'Bot Traffic Spike',
    description: 'High volume of bot traffic on signup page.',
    priority: 'HIGH',
    status: 'RESOLVED',
    createdDate: '2024-10-20T22:00:00Z',
    resolvedDate: '2024-10-21T04:00:00Z',
    categoryId: 1,
    createdBy: 1,
    assignedAgent: 2,
  },
  {
    id: 26,
    title: 'Typo in Welcome Email',
    description: '"Sentinel" spelled as "Sentinal".',
    priority: 'LOW',
    status: 'OPEN',
    createdDate: '2024-10-24T12:00:00Z',
    categoryId: 5,
    createdBy: 5,
  },
  {
    id: 27,
    title: 'Webhook Not Firing',
    description: 'Subscription webhooks not reaching endpoint.',
    priority: 'HIGH',
    status: 'OPEN',
    createdDate: '2024-10-24T14:30:00Z',
    categoryId: 3,
    createdBy: 4,
  },
  {
    id: 28,
    title: 'Avatar Upload Failing',
    description: 'Users cannot upload PNG avatars.',
    priority: 'LOW',
    status: 'IN_PROGRESS',
    createdDate: '2024-10-23T15:00:00Z',
    categoryId: 4,
    createdBy: 5,
    assignedAgent: 3,
  },
  {
    id: 29,
    title: 'Database Connection Pool Full',
    description: 'Max connections reached on DB.',
    priority: 'CRITICAL',
    status: 'RESOLVED',
    createdDate: '2024-10-22T10:00:00Z',
    resolvedDate: '2024-10-22T11:00:00Z',
    categoryId: 1,
    createdBy: 1,
    assignedAgent: 2,
  },
  {
    id: 30,
    title: 'Terms of Service Update',
    description: 'Legal requires update to TOS.',
    priority: 'LOW',
    status: 'OPEN',
    createdDate: '2024-10-24T16:00:00Z',
    categoryId: 5,
    createdBy: 1,
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 1,
    text: "We're seeing critical latency in the checkout flow. Dashboard is showing node-88 in unhealthy state. Can we get an immediate diagnostic?",
    timestamp: '2024-10-24T14:32:00Z',
    ticketId: 1,
    senderId: 4,
  },
  {
    id: 2,
    text: "Checking logs now, Elena. It looks like a memory leak on the worker process. I'm initiating a node rotation to clear the queue while we patch the deployment.",
    timestamp: '2024-10-24T14:45:00Z',
    ticketId: 1,
    senderId: 2,
  },
];

export const MOCK_WORKLOADS: AgentWorkload[] = [
  { agentId: 2, currentWorkload: 8, maxCapacity: 10 },
  { agentId: 3, currentWorkload: 4, maxCapacity: 10 },
  { agentId: 6, currentWorkload: 9, maxCapacity: 10 },
  { agentId: 7, currentWorkload: 0, maxCapacity: 10 },
  { agentId: 8, currentWorkload: 2, maxCapacity: 10 },
];
